### PR TITLE
Reorder soft-deleted records

### LINKED ISSUE #31: Soft deleting models are not reordered as expected
I have a model which uses the `SoftDeletes trait` and the `SortableTrait`. On the front-end of my app I'm displaying only the ordered non-trashed models, but on the back-end I'm including the trashed models, which can be reordered.

The soft deleting trait adds a constraint when the `setNewOrder` method is looping over the ids, therefore the order column is updated only on the non-trashed models. This is a bug because the new order is not synced across all the given models, which gives us duplicate order numbers, and that leads to unexpected results.

I'm happy to submit a PR if this is something that should be fixed. Thanks!

### PR DESCRIPTION
**Pull request by sebdesign**
Adds the ability to reorder models that use the `SoftDeletes` trait.

Fixes #31

### CODE REVIEW

File: src/SortableTrait.php [hunk 1]
```diff
@@ -49,6 +50,32 @@ public function scopeOrdered(Builder $query, string $direction = 'asc')
...
 
     /**
+     * Query records which are ordered above the given position.
+     *
+     * @param \Illuminate\Database\Eloquent\Builder $query
+     * @param int $position
+     *
+     * @return \Illuminate\Database\Query\Builder
+     */
+    public function scopeAbove(Builder $query, int $position)
```
Comment (freekmurze) [inline src/SortableTrait.php]: I don't like scopes being added that solely exist for internal working and will not be used publicly. Could you remove these?

**Comment by freekmurze** [comment]
Thanks!

**Comment by sebdesign** [comment]
You're welcome! I owe you a postcard. 📮
